# `waypoint` data

The waypoint data appears to be defined at the stage level.

In [3]:
# Load in the required pandas package
import pandas as pd

# Generate the API URL pattern
dakar_api_template = "https://www.dakar.live.worldrallyraidchampionship.com/api/{path}"

# Define the year
YEAR = 2025
# Define the category
CATEGORY = "A"
# Define the stage
STAGE = 1

# Define the API path to the stage resource
# Use a Python f-string to instantiate variable values directly
waypoint_path = f"waypoint-{YEAR}-{CATEGORY}-{STAGE}"

# Define the URL
waypoint_url = dakar_api_template.format(path=waypoint_path)

# Preview the path and the URL
waypoint_path, waypoint_url

('waypoint-2025-A-1',
 'https://www.dakar.live.worldrallyraidchampionship.com/api/waypoint-2025-A-1')

In [18]:
_waypoint_df = pd.read_json(waypoint_url)
_waypoint_df

,_bind,_origin,_id,_key,_updatedAt,_parent,waypoints
0,waypoint-2025-A-1,waypoint-2025-A-1,4ae51c74af545e1d1735bdb5c3cd74ae,_id,1736183717267,stage-2025-A:4ae51c74af545e1d1735bdb5c3cd74ae,"[{'kilometerPoint': 38.83, 'checkpoint': 1, 'c..."

The response type is a single result in a list. We can more conveniently parse the results out of this dataframe as follows:

In [19]:
stage_code = _waypoint_df.iloc[0]["_origin"]

waypoint_df = pd.json_normalize(_waypoint_df["waypoints"].explode())
waypoint_df["Year"] = YEAR
waypoint_df["Stage"] = STAGE
waypoint_df["Category"] = CATEGORY
waypoint_df["stage_code"] = stage_code

waypoint_df

,kilometerPoint,checkpoint,code,kilometerPointDisplay,id,hidden,isCHR,isBRP,isASG,isLBL,groups,isFirstDss,Year,Stage,Category,stage_code
0,38.83,1,01207,39.0,125111,False,True,False,False,False,None,NaN,2025,1,A,waypoint-2025-A-1
1,91.04,2,01216,92.0,125112,False,True,False,False,False,None,NaN,2025,1,A,waypoint-2025-A-1
2,121.18,3,01218,122.0,125113,False,True,False,False,False,None,NaN,2025,1,A,waypoint-2025-A-1
3,150.72,4,01220,151.0,125114,False,True,False,False,False,None,NaN,2025,1,A,waypoint-2025-A-1
4,181.18,5,01222,182.0,125115,False,True,False,False,False,None,NaN,2025,1,A,waypoint-2025-A-1
5,212.54,6,01224,213.0,125116,False,True,False,False,False,None,NaN,2025,1,A,waypoint-2025-A-1
6,243.32,7,01227,244.0,125117,False,True,False,False,False,None,NaN,2025,1,A,waypoint-2025-A-1
7,287.02,8,01230,288.0,125119,False,True,False,False,False,None,NaN,2025,1,A,waypoint-2025-A-1
8,329.07,9,01233,330.0,125120,False,True,False,False,False,None,NaN,2025,1,A,waypoint-2025-A-1
9,365.15,10,01237,366.0,125121,True,True,False,False,False,None,NaN,2025,1,A,waypoint-2025-A-1
10,412.95,11,012AS,413.0,125122,False,False,False,False,True,None,NaN,2025,1,A,waypoint-2025-A-1
11,0.00,0,012DS,0.0,125110,False,False,False,False,False,None,True,2025,1,A,waypoint-2025-A-1
12,NaN,999,01ASS,NaN,125123,False,False,False,False,True,None,NaN,2025,1,A,waypoint-2025-A-1

The waypoint data provides the distance into the stage of each waypoint, along with a wayuppint code and a waypoint ordering. The boolean flag information does not appear to be immediately useful.